name: Deploy Glue Infrastructure

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  SRC_CD_BUCKET: 'src-code-bucket-learning'
  PROJECT_KEY_PREFIX: 'SecondPOC'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::585008084392:role/GithubRoleForAwsDemo'
          aws-region: 'eu-north-1'

      - name: Upload Glue Script to S3
        run: |
          TIMESTAMP=$(date +%s)
          aws s3 cp ./scripts/s3_to_parquet_job.py s3://$SRC_CD_BUCKET/$PROJECT_KEY_PREFIX/glue-job-scripts/s3_to_parquet_job-${TIMESTAMP}.py
          aws s3 cp ./scripts/s3_to_parquet_job.py s3://$SRC_CD_BUCKET/$PROJECT_KEY_PREFIX/glue-job-scripts/s3_to_parquet_job-latest.py

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file ./cloudformation/glue-job.yaml  \
            --stack-name glue-stack \
            --parameter-overrides \
              ScriptBucket=$SRC_CD_BUCKET \
              ScriptKey=$PROJECT_KEY_PREFIX/glue-job-scripts/s3_to_parquet_job-latest.py \
            --capabilities CAPABILITY_NAMED_IAM
