name: Deploy Glue Infrastructure

on:
  push:
    branches: [main]

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required for repository access

env:
  AWS_REGION: eu-north-1
  SRC_CD_BUCKET: 'src-code-bucket-learning'
  PROJECT_KEY_PREFIX: 'SecondPOC'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GitHub OIDC Token
        run: |
          echo "GITHUB OIDC TOKEN URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "TOKEN REQUEST: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        env:
          ACTIONS_STEP_DEBUG: true  # Enable debugging

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585008084392:role/GithubRoleForAwsDemo
          role-session-name: GitHubActions
          aws-region: eu-north-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Upload Glue Script to S3
        run: |
          TIMESTAMP=$(date +%s)
          aws s3 cp ./scripts/s3_to_parquet_job.py s3://$SRC_CD_BUCKET/$PROJECT_KEY_PREFIX/glue-job-scripts/s3_to_parquet_job-${TIMESTAMP}.py
          aws s3 cp ./scripts/s3_to_parquet_job.py s3://$SRC_CD_BUCKET/$PROJECT_KEY_PREFIX/glue-job-scripts/s3_to_parquet_job-latest.py

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file ./cloudformation/glue-job.yaml  \
            --stack-name glue-stack \
            --parameter-overrides \
              ScriptBucket=$SRC_CD_BUCKET \
              ScriptKey=$PROJECT_KEY_PREFIX/glue-job-scripts/s3_to_parquet_job-latest.py \
            --capabilities CAPABILITY_NAMED_IAM
